name: Check for broken links

on:
  push:
    branches: [ master, main ]
    paths:
      - "assets/**"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "!lighthouse_results/**"
  pull_request:
    branches: [ master, main ]
    paths:
      - "assets/**"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "!lighthouse_results/**"

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build the site so _site/ exists and responsive images get generated
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - name: Install ImageMagick & WebP
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick webp

      - name: Build site
        run: |
          export JEKYLL_ENV=production
          bundle exec jekyll build --lsi

      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          # Check ONLY the built HTML and resolve absolute /assets paths against _site
          args: >
            --base "./_site"
            --verbose --no-progress
            "_site/**/*.html"
            --exclude "data:*"
